name: skyhookt
favicon: null
layout_spectrum: 0.6583547757472843
typography_spectrum: 0.8882109574042261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24118349328637123
  lightness: 0.33747247606515884
  saturation: 0.5355791277252138
  rhythmicContrast: 0.5324959005229175
purpose: []
